#!/bin/bash -e

if [ -z "$TESTSUITE_DIR" ]
then
  TESTSUITE_DIR=$(pwd)
fi

frontend=`mktemp`
${TESTSUITE_DIR}/kabootstrap-setup $2 $3 $frontend $4

if [ "$1" = "test" ]
then
  ${TESTSUITE_DIR}/kadeploy-testsuite $2 $(cat $frontend) "$4" $5
else
  ${TESTSUITE_DIR}/kanalyze-testsuite $2 $(cat $frontend) "$4" $5
fi

rm -f $frontend
