#!/bin/bash -e

if [ -z "$TESTSUITE_DIR" ]
then
  TESTSUITE_DIR=$(pwd)
fi

frontend=`mktemp`
${TESTSUITE_DIR}/kabootstrap-setup $2 $3 $frontend $4

if [ "$1" -eq "test" ]
then
  ${TESTSUITE_DIR}/kadeploy-testsuite $2 $(cat $frontend) $4
else
  ${TESTSUITE_DIR}/kanalyse-testsuite $2 $(cat $frontend)
fi

rm -f $frontend
