#!/usr/bin/ruby

$:.unshift File.dirname(__FILE__)

require 'common-g5k'

LOGS_DIR=File.join(TESTSUITE_DIR,'logs')

unless ARGV.size >= 2
  vars = KADEPLOY_ENV_VARS.inject(''){|tmp,var| tmp << "  #{var} (default: #{self.class.const_get(var)})\n"}
  error("usage: #{$0} [git:|gerrit:]<commit/branch> <version> [<sources dir>]\ncustomizable env vars:\n#{vars}\nsamples:\n  #{$0} master 3.1.8 (git is used by default)\n  #{$0} git:3.1.7 3.1.7 kadeploy3-sources/\n  #{$0} git:5f4b6c54949b0769596b10087c1d14150930d84f 7\n  #{$0} gerrit:refs/changes/27/1027/13 3.1.7")
end
$commit=ARGV[0]
$version=ARGV[1]
$sources=ARGV[2]

cmd("mkdir -p #{LOGS_DIR}")

puts "Make the reservation"
vars = ''
KADEPLOY_ENV_VARS.each do |var|
  vars << " #{var}=\"#{ENV[var]}\"" if ENV[var]
end
env = (vars.empty? ? '' : "export #{vars};")
$commitfile = $commit.gsub('/','_').gsub(':','-')
ret=cmd("oarsub -t deploy -n #{$commitfile} -l {\"type='kavlan-local'\"}/vlan=1+cluster=2/nodes=2,walltime=3 '#{env} #{File.join(TESTSUITE_DIR,'run-testsuite')} #{$commit} #{$version} #{$sources}'")

$jobid=ret.split("\n").grep(/OAR_JOB_ID/).to_s.split("=")[1]

cmd("echo \"#{$jobid}\" > #{LOGS_DIR}/#{$commitfile}.jobid")

trap('INT') {
  puts "Deleting OAR JOB"
  cmd("oardel #{$jobid}")
  exit 1
}

puts "Job ID: #{$jobid}"
puts "Wait for the job to terminate"
out = ''
begin
  sleep 20
  out = cmd("oarstat -s -j #{$jobid}")
end until out.grep(/Terminated|Error/).size > 0

puts "Job done"
outfile = "#{LOGS_DIR}/#{$commitfile}.stdout"
cmd("mv OAR.#{TAG}.#{$jobid}.stdout #{errfile}")
errfile = "#{LOGS_DIR}/#{$commitfile}.stderr"
cmd("mv OAR.#{TAG}.#{$jobid}.stderr #{errfile}")

puts '=== STDOUT ==='
puts File.read(outfile) if File.readable?(outfile)
puts '=============='
puts ''
puts '=== STDERR ==='
puts File.read(errfile) if File.readable?(errfile)
puts '=============='

if out.grep(/Error/).size > 0
  exit 1
else
  exit 0
end
