#!/bin/bash -e
#
# debirf module: kadeploy-addons
#
# The debirf scripts were written by
# Jameson Rollins <jrollins@fifthhorseman.net>
# and
# Daniel Kahn Gillmor <dkg@fifthhorseman.net>.
#
# They are Copyright 2007, and are all released under the GPL,
# version 3 or later.
#
# This module has been added by
# Emmanuel Jeanvoine <emmanuel.jeanvoine@inria.fr>


echo "Configure some stuffs for Kadeploy"
mkdir -p $DEBIRF_ROOT/mnt/dest
mkdir -p $DEBIRF_ROOT/rambin
mkdir -p $DEBIRF_ROOT/mnt/tmp
mkdir -p $DEBIRF_ROOT/usr/local/bin

rm -f /var/lib/dhcp/dhclient*.leases

cp $DEBIRF_BUILDD/kadeploy_specific/scripts/* $DEBIRF_ROOT/usr/local/bin
chmod +x $DEBIRF_ROOT/usr/local/bin/*

cat > "$DEBIRF_ROOT/etc/rc.local" <<'EOF'
#!/bin/bash -e

# parse kadeploy-specific kernel command line arguments
netdev=eth0
for param in $(cat /proc/cmdline); do
  if printf "%s" "$param" | egrep -q '^ETH_DEV='
  then
    netdev="$(printf "%s" "$param" | cut -f2 -d=)"
  fi
done

ifup "$netdev"=dhcp
if [ ! -f "/var/lib/dhcp/dhclient.${netdev}.leases" ]
then
  exit 1
fi

(while true; do nc -l -p 25300; done) &

exit 0
EOF

cat > "$DEBIRF_ROOT/etc/dhcp/dhclient-enter-hooks.d/hostname" <<'EOF'
if [ -n $new_host_name ] && [ -n $new_domain_name ]
then
        echo "$new_host_name.$new_domain_name" > /etc/hostname
        /bin/hostname "$new_host_name.$new_domain_name"
        if [ -n $new_ip_address ]
        then
                echo "$new_ip_address $new_host_name.$new_domain_name $new_host_name" >> /etc/hosts
        fi
fi
EOF

mkdir -p $DEBIRF_ROOT/root/.ssh
cat $DEBIRF_BUILDD/kadeploy_specific/ssh/*.pub >> $DEBIRF_ROOT/root/.ssh/authorized_keys

# Add recent megaraid drivers for new clusters at Rennes and Nancy
#
cp $DEBIRF_BUILDD/kadeploy_specific/megaraid_sas-06.806.08.00-1_Debian7.0.amd64.deb $DEBIRF_ROOT/root
debirf_exec dpkg -i /root/megaraid_sas-06.806.08.00-1_Debian7.0.amd64.deb
rm $DEBIRF_ROOT/root/megaraid_sas-06.806.08.00-1_Debian7.0.amd64.deb

# depmod to create module list
KVERS=$(ls -1 -t "$DEBIRF_ROOT/lib/modules" | head -n1)
echo "generating modules.dep..."
debirf_exec depmod -a "$KVERS"

