#!/bin/bash

now=`date +"%F_%T"`
[ -e /etc/kadeploy3/server_conf.yml ] && cp /etc/kadeploy3/server_conf.yml /etc/kadeploy3/server_conf-save-$now.yml || exit 0
[ -e /etc/kadeploy3/clusters.yml ] && cp /etc/kadeploy3/clusters.yml /etc/kadeploy3/clusters-save-$now.yml || exit 0
[ -e /etc/kadeploy3/cmd.yml ] && cp /etc/kadeploy3/cmd.yml /etc/kadeploy3/cmd-save-$now.yml || exit 0
