#!/bin/bash

now=`date +"%F_%T"`
[ -e /etc/kadeploy3/conf ] && cp /etc/kadeploy3/conf /etc/kadeploy3/conf-save-$now || exit 0
[ -e /etc/kadeploy3/clusters ] && cp /etc/kadeploy3/clusters /etc/kadeploy3/clusters-save-$now || exit 0
[ -e /etc/kadeploy3/nodes ] && cp /etc/kadeploy3/nodes /etc/kadeploy3/nodes-save-$now || exit 0
[ -e /etc/kadeploy3/cmd ] && cp /etc/kadeploy3/cmd /etc/kadeploy3/cmd-save-$now || exit 0
