#!/bin/bash
#
# kadeploy        Startup script for the Kadeploy 3 server
#
# processname: kadeploy3d
#
### BEGIN INIT INFO
# Provides: kadeploy
# Should-Start: distcache
# Short-Description: start and stop Kadeploy 3 Server
# Description: Kadeploy 3 server.
### END INIT INFO

# chkconfig: 2345 90 10

# Source function library.
. /etc/rc.d/init.d/functions


prog="Kadeploy 3"
kadeploy3d=/usr/sbin/kadeploy3d
rundir=/var/run/kadeploy3d
pidfile=${rundir}/kadeploy3d.pid
args="--pidfile $pidfile --detach"
lockfile=/var/lock/subsys/kadeploy3d
user=deploy
RETVAL=0

start() {
	      echo -n "Starting $prog: "
        [ -d $rundir ] || (mkdir $rundir && chown $user $rundir)
	[ -e $pidfile ] && [ -e /proc/`cat $pidfile` ] && echo "Daemon already running" && return 1
        [ -e $pidfile ] || ( touch $pidfile && chown $user:$user $pidfile )
        daemon --pidfile=${pidfile} --user=$user "$kadeploy3d $args"
	RETVAL=$?
	PID=`cat $pidfile`
        echo
	( [ -n "$PID" ] && [ -x /proc/${PID} ] ) || return 1
	[ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}

stop() {
        echo -n "Stopping $prog: "
        killproc -p ${pidfile} -d 3 $kadeploy3d
        RETVAL=$?
        echo
        # Remove the PID file if the process was killed using SIGKILL
	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

reload() {
        reloadfile=$rundir/reload
        rm -f $reloadfile
        killproc -p "$pidfile" "$kadeploy3d" -HUP
        while [ ! -s $reloadfile ]
        do
                sleep 1
        done
        sed '1d' $reloadfile >&2
        [ "$(sed '1q' $reloadfile)" = "0" ]
        RETVAL=$?
}

case "$1" in
  start)
        start
	;;
  stop)
        stop
	;;
  status)
	status -p ${pidfile} $kadeploy3d
        RETVAL=$?
  ;;
  reload|force-reload)
        reload
        [ $RETVAL != "0" ] && [ "$1" = "force-reload" ] && stop && start
  ;;
  restart)
	stop
	start
  ;;
  *)
    	  echo $"Usage: $prog {start|stop|restart|reload|force-reload|status}"
        RETVAL=3
esac

exit $RETVAL



