#!/bin/sh

mknod null c 1 3
mknod zero c 1 5
mknod tty c 5 0
mknod console c 5 1
mknod urandom c 1 9

# create ttyS
for i in 64 65 66 67 68 69; do
	x=$(($i-64));
	mknod ttyS$x c 4 $i;
done

# create loop devices
for i in 0 1 2 3 4 5 6 7; do 
	mknod loop$i b 7 $i;
done

# create ramdisks
for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
	mknod ram$i b 1 $i;
done

# create hdax
mknod hda b 3 0
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
        mknod hda$i b 3 $i;
done	

# create hdbx
mknod hdb b 3 64
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
	x=$(($i+64));
	mknod hdb$i b 3 $x;
done

# create hdcx
mknod hdc b 22 0
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
        mknod hdc$i b 22 $i;
done
	
# create hddx
mknod hdd b 22 64
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
        x=$(($i+64));
	mknod hdd$i b 22 $x;
done
		
# create sdax
mknod sda b 8 0
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
        mknod sda$i b 8 $i;
done

# create sdbx
mknod sdb b 8 16
for i in 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31; do
	x=$(($i-16));
	mknod sdb$x b 8 $i;
done

#create cciss
mkdir cciss
cd cciss
mknod c0d0 b 104 0
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
	mknod c0d0p$i b 104 $i
done
