#!/bin/bash -e

[ -e "${KADEPLOY_BLOCK_DEVICE}" ] || ( echo "device not found '${KADEPLOY_BLOCK_DEVICE}'" 1>&2; exit 1 )

### Create GRUB directory ###
GRUBDIR=$KADEPLOY_ENV_EXTRACTION_DIR/boot/grub
mkdir -p $GRUBDIR


### Generation of the device map ###
DEVICEMAP=${GRUBDIR}/device.map
echo "(hd0) ${KADEPLOY_BLOCK_DEVICE}" > $DEVICEMAP


### Install grub on the deployment partition ###
grub-install --root-directory=$KADEPLOY_ENV_EXTRACTION_DIR $KADEPLOY_DEPLOY_PART


### Generation of the menu file grub.cfg ###
MENUFILE=${GRUBDIR}/menu.lst

## Get grub partition number ##
let grubpart=${KADEPLOY_DEPLOY_PART_NUM}-1

## Generate the options considering on the operating system ##
case $KADEPLOY_OS_KIND in
  "linux")
    opts="  kernel $KADEPLOY_ENV_KERNEL $KADEPLOY_ENV_KERNEL_PARAMS"$'\n'
    [ -n "$KADEPLOY_ENV_INITRD" ] && opts+="  initrd $KADEPLOY_ENV_INITRD"$'\n'
    ;;

  "xen")
    opts="  kernel $KADEPLOY_ENV_HYPERVISOR $KADEPLOY_ENV_HYPERVISOR_PARAMS"$'\n'
    opts+="  module $KADEPLOY_ENV_KERNEL $KADEPLOY_ENV_KERNEL_PARAMS"$'\n'
    [ -n "$KADEPLOY_ENV_INITRD" ] && opts+="  module $KADEPLOY_ENV_INITRD"$'\n'
    ;;

  "bsd")
    opts="rootnoverify (hd0,${grubpart})"$'\n'
    opts+="makeactive"$'\n'
    opts+="chainloader +1"$'\n'
    ;;

  "windows")
    opts="rootnoverify (hd0,${grubpart})"$'\n'
    opts+="makeactive"$'\n'
    opts+="chainloader +1"$'\n'
    ;;
  *)
    echo "Unknown operating system '${KADEPLOY_OS_KIND}'" 1>&2
    exit 1
    ;;
esac

## Write the menu file ##
IFS=''
cat <<EOF > $MENUFILE
default 0

title ${KADEPLOY_OS_KIND}
root (hd0,${grubpart})
$opts
EOF

