# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "irisa_debian-8.0"
  config.vm.box_url = "https://vagrant.irisa.fr/boxes/irisa_debian-8.0.box"
  config.vm.provision "shell", path: "script.sh"
end
