#!/usr/bin/ruby

require 'socket'
require 'resolv'

MAX_VMS=18

# Constraints
MAX_VM_PER_CORE = 2

# Sizes in Mo
RAM_SIZE = 350
FS_SIZE = 564

FS_TYPE = 'qcow2'
FS_FILE = "disk.#{FS_TYPE}"
#NET_MODEL = 'e1000'
HOST_FREE_MEM_SIZE = 1024

TMP_DIR = '/tmp/katestbed'

def cmd(cmd,critical=true)
  ret = `#{cmd}`
  if critical and !$?.success?
    $stderr.puts "error when executing '#{cmd}': #{ret}"
    exit 1
  end
  ret
end

myip=Resolv.getaddress(Socket.gethostname)

# Get memory info
meminfo = File.read('/proc/meminfo')
totmem = nil
meminfo.each do |line|
  totmem = Regexp.last_match(1).to_i/1024 if line =~ /^MemTotal:\s*(\S+)\s*.*$/
end

unless totmem
  $stderr.puts 'Unavailable to get meminfo'
  exit 1
end

cpuinfo = File.read('/proc/cpuinfo')
totcores = 0
cpuinfo.each do |line|
  totcores += 1 if line =~ /^processor\s*:\s*\S+.*$/
end

nbvm = (totmem-HOST_FREE_MEM_SIZE)/(FS_SIZE + RAM_SIZE)

maxvms = (MAX_VM_PER_CORE * totcores)

ret = (nbvm <= maxvms ? nbvm : maxvms).to_i

if ret < MAX_VMS
  puts ret
else
  puts MAX_VMS
end
