#!/usr/bin/ruby

require 'socket'
require 'resolv'

VM_RAM = '512M'
VM_NET_MODEL = 'e1000'
VM_FS = '8G'

def cmd(cmd,critical=true)
  ret = `#{cmd}`
  if critical and !$?.success?
    puts "error when executing '#{cmd}': #{ret}"
    exit 1
  end
  ret
end

myip=Resolv.getaddress(Socket.gethostname)

cmd("killall kvm &>/dev/null; true")

ARGF.each do |line|
  if line =~ /^\s*(\S+)\s+(\S+)\s+(\S+)\s+#{myip}\s*$/
    vmname = Regexp.last_match(1)
    vmip = Regexp.last_match(2)
    vmmac = Regexp.last_match(3)
    file = cmd("mktemp --tmpdir #{vmname}_XXXXXXXX.rawfs").chomp
    cmd("qemu-img create -f raw #{file} #{VM_FS}")
    cmd("screen -d -m -S #{vmname} kvm -net nic,macaddr=#{vmmac},model=#{VM_NET_MODEL} -net tap -boot n -m #{VM_RAM} -drive file=#{file} -name #{vmname} -curses")
    puts "Started #{vmname} (mac:#{vmmac})"
  end
end

