forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib', '4.1.0'
mod 'puppetlabs/firewall', '1.0.2'
mod 'thias/bind', '0.5.0'
mod 'puppetlabs/dhcp',
  :git => "git://github.com/puppetlabs/puppetlabs-dhcp.git",
  :ref => '0.2.0'
mod 'puppetlabs/tftp', '0.2.1'
mod 'puppetlabs/mysql', '2.2.1'
