#!/bin/sh

kernelPath=$1
initrdPath=$2
shift
shift
destPartAndParams=$@

/bin/sync

#echo "Setting Kexec parameters"
/sbin/kexec -l $kernelPath --initrd=$initrdPath --append="root=$destPartAndParams"
#echo "Running Kexec"
/sbin/start-stop-daemon -S -x /usr/local/bin/run_kexec -b
